version: "3"

services:
  redis-master:
    image: "bitnami/redis"
    container_name: redis-master
    environment:
      - REDIS_REPLICATION_MODE=master
      - REDIS_PASSWORD=str0ng_passw0rd
    ports:
      - "6379"
  redis-replica:
    image: "bitnami/redis"
    environment:
      - REDIS_REPLICATION_MODE=slave
      - REDIS_MASTER_HOST=redis-master
      - REDIS_MASTER_PASSWORD=str0ng_passw0rd
      - REDIS_PASSWORD=str0ng_passw0rd
    ports:
      - "6379"
    depends_on:
      - redis-master
  redis-sentinel:
    image: "bitnami/redis-sentinel"
    environment:
      - REDIS_MASTER_SET=mymaster
      - REDIS_MASTER_HOST=redis-master
      - REDIS_MASTER_PASSWORD=str0ng_passw0rd
      - REDIS_SENTINEL_DOWN_AFTER_MILLISECONDS=10000
    depends_on:
      - redis-master
      - redis-replica
    ports:
      - "26379"
  app:
    image: "redis-learning"
    container_name: redis-learning
    environment:
      - SPRING_REDIS_SENTINEL_MASTER=mymaster
#      - SPRING_REDIS_SENTINEL_NODES=redis-sentinel:26379
      - SPRING_REDIS_SENTINEL_PASSWORD=str0ng_passw0rd
      - SPRING_REDIS_PASSWORD=str0ng_passw0rd
      - SPRING_REDIS_TIMEOUT=PT1S
      - SPRING_REDIS_CONNECT_TIMEOUT=PT0.5S
#      - BPL_DEBUG_ENABLED=true
#      - BPL_DEBUG_PORT=8000
    ports:
      - "8080:8080"
#      - "8000:8000"
    depends_on:
      - redis-sentinel
#  debug:
#    image: alpine
#    container_name: debug
#    command: tail -f /dev/null
#    depends_on:
#      - app