DROP TABLE IF EXISTS APPTS;
CREATE TABLE APPTS (
  ID INT NOT NULL,
  USER_ID INT NOT NULL,
  START_DT_TIME VARCHAR(50) NOT NULL,
  END_DT_TIME VARCHAR(50) NOT NULL,
  COMMENT VARCHAR(200),
  PRIMARY KEY (ID));

